made zoom link
DataGood-Berkeley/website pull request #40
Opened 2021-01-04 00:25 UTC by nhudait

2021-01-04 00:26 UTC, PotatoParser requested changes
Looks good! Just a small lint needed.

2021-01-04 00:26 UTC, PotatoParser commented on index.js
> +  res.redirect('https://berkeley.zoom.us/j/98351933735?pwd=dE0yeEl5OEZyd05MOC9VbWxKOXUxQT09')
Missing semicolon

2021-01-11 04:13 UTC, nhudait commented on index.js
> +  res.redirect('https://berkeley.zoom.us/j/98351933735?pwd=dE0yeEl5OEZyd05MOC9VbWxKOXUxQT09')
i think i added it

2021-01-11 04:13 UTC, PotatoParser approved these changes
Perfect!

2021-01-11 04:13 UTC, merged